version: '3.8'
services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rr-challenge
      POSTGRES_PASSWORD: rr-challenge
      POSTGRES_DB: cryptocurrency_transactions
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d

volumes:
  pg-data: